### PR TITLE
Moved NavBar to App.js Added some functionality to the Login/Logout, …

### PR DESCRIPTION
**Pull request by lynntfuzz**
…but it still needs more

### CODE REVIEW

**Comment by jobimathai1** [comment]
Hey Lynn, this branch has conflicts.

**Comment by lynntfuzz** [comment]
Oops

**Comment by lynntfuzz** [comment]
Want me just to merge it?

**Comment by jobimathai1** [comment]
Sure let’s try it?

**Comment by lynntfuzz** [comment]
ok I resolved the conflicts

**Review by jobimathai1 — APPROVED** [review]

**Pull request merged**
